-- MySQL Script generated by MySQL Workbench
-- Tue Apr 28 15:15:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema taal_arquitetura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taal_arquitetura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taal_arquitetura` DEFAULT CHARACTER SET utf8 ;
USE `taal_arquitetura` ;

-- -----------------------------------------------------
-- Table `taal_arquitetura`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taal_arquitetura`.`clientes` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `endereco` VARCHAR(150) NULL DEFAULT NULL,
  `cep` VARCHAR(8) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `telefone` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Clientes cadastrados na TAAL Arquitetura.';


-- -----------------------------------------------------
-- Table `taal_arquitetura`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taal_arquitetura`.`servicos` (
  `codigo_servico` VARCHAR(5) NOT NULL,
  `nome_servico` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(800) NULL DEFAULT NULL,
  `valor_hora` FLOAT NULL DEFAULT NULL,
  `valor_maior_400m2` FLOAT NULL DEFAULT NULL,
  `valor_menor_400m2` FLOAT NULL DEFAULT NULL,
  `valor_unico` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_servico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taal_arquitetura`.`orcamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taal_arquitetura`.`orcamentos` (
  `codigo` VARCHAR(5) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `data_orcamento` DATE NULL DEFAULT NULL,
  `codigo_servico` VARCHAR(5) NOT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  `valor_total` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`, `codigo_servico`),
  INDEX `fk_clientes` (`cpf` ASC) VISIBLE,
  INDEX `fk_servicos` (`codigo_servico` ASC) VISIBLE,
  CONSTRAINT `fk_clientes`
    FOREIGN KEY (`cpf`)
    REFERENCES `taal_arquitetura`.`clientes` (`cpf`),
  CONSTRAINT `fk_servicos`
    FOREIGN KEY (`codigo_servico`)
    REFERENCES `taal_arquitetura`.`servicos` (`codigo_servico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
